apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
  namespace: argocd
spec:
  destination:
    namespace: flask-app
    server: https://kubernetes.default.svc
  project: default
  source:
    path: infra/charts/flask-app
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  helm:
    valueFiles:
      - secrets+age-import:///helm-secrets-private-keys/key.txt?../../values/flask-app.yaml
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
