stages:
  - test

.interruptible_job:
  interruptible: true

test-lint-job:
  stage: test
  extend:
    - .interruptible_job
  image:
    name: python:3.12.0-alpine
    pull_policy: if-not-present
  allow_failure: true
  script:
    - pip install ruff
    - ruff format --check
    - ruff check
