spec:
    source:
        repoURL: https://89.169.171.91/zhilovhub/optimalcityproject.git
        targetRevision: HEAD
    destination:
        server: https://kubernetes.default.svc
    registry: 89.169.171.91:7000/zhilovhub/optimalcityproject/flask-app