applications:
    apps:
        namespace: ENC[AES256_GCM,data:oge/qPMw,iv:XY58vpRkC2GsTrQi6qmrI6Dh1cgKntQjhtL78vFnXNk=,tag:OGP+rfTT31/YNwP4Mhp6XA==,type:str]
        project: ENC[AES256_GCM,data:U7gVP0dNYw==,iv:QlCz7ukYUyxM454SYzbma0XKg8nhTLon+YLPP0S0kdQ=,tag:60xYg0aiI1FMskawkmbpuw==,type:str]
        source:
            helm:
                valueFiles:
                    - ENC[AES256_GCM,data:b/c77jx3nvyWWuhnxnA5o87G9FKksw==,iv:I5MXHEqj9TUIFQ2jEiWrKn34qBIVKMsJ0QG54X0ANhk=,tag:kl84scRE3AFKmD25eGZFNw==,type:str]
            path: ENC[AES256_GCM,data:/C27YDtNasm34wUK6RPdpT4=,iv:0O/y1HrhIMoTKsD7463GcY8LcvjfpELw6HfWGjQMtvg=,tag:xIqKwHuXCAV/+oX/gWm/Rg==,type:str]
            repoURL: ENC[AES256_GCM,data:gZkVPSCNobXpTvLGq1SxPSqeS3182Ttyooc+FLmxM1+jOLgqxR6fDkO6LglnoZ7juFEAAEYy,iv:401B5YPAWKWGdIFZmxqCzeHXWzPcJG4JnP/M/6PnLec=,tag:OWoeT0O6EIvUrNoMkRooYg==,type:str]
        destination:
            namespace: ENC[AES256_GCM,data:YDqz0I99,iv:d2tBSdPE0Qoh+h7pdNhg2P1NiQPKqyFuVTDSPFWmS5Q=,tag:snZYs/+sUqznrJHz3xCUaw==,type:str]
            server: ENC[AES256_GCM,data:LdN6T1U5FbhfTDhud1UQK24JUl3/RGZUwVcfABce,iv:3kSgIIrgRIpefEjSktsncYPenHA8Qk8+f5iGXL1kkmQ=,tag:weoqqUD1MK+q3N9NkaMblQ==,type:str]
        syncPolicy:
            automated: {}
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c9zz7wdv56gdsycv5l60zhjeng7y4gtm7qhzd9qrzc2e332lk3vsrwsxuy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVW9ia09kVmdIeGlnbDl5
            NkpTMXpjS1MxcWJYVkMxSTYzYi9iQ04wcEdjCnlSY0ZXRUQydFBnUDZXWnh4YUxO
            RDNtUnNsOTNkaXJLMWQ1K1FPVFhydW8KLS0tIDJqeVV3NW5UVEVwQlBOR01tVTFm
            Yzh0ZUx1Zm9VTDV5Y01BQm1qVFhBd0UKdOdXQ+O0YKJwubQYsYQOCj3t9EOaLxeq
            lPWE1LzvfeNTKdnYXLnvi6QN0/n66FdaT4YjCxZGoQlf1lwdDrvTBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-20T21:31:12Z"
    mac: ENC[AES256_GCM,data:cbPWxpGnXkqkg41z2hEKz/ZdxSdNyIUa+48BtXHolPmdF2sYd5e8ut1rnX9hq0jrb5YYJr87P2M9SVKkzs3ZoTzfibVoYkJmodAk63d8FTHb/BATKfprCjfZ/5527y93Uk83dhXh8z9vaGcKQkPEBVjF1fiORJLWz/dVoDUIXKU=,iv:KH8o6HfiGCdqZxhER8av4KB7sYDqnt9jiHl8AVw4EMg=,tag:nSHjAQlBvQSs9OnBdAZPYw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
