applications:
    apps:
        namespace: ENC[AES256_GCM,data:urncJ9Mj,iv:RxlthV0042zKL/1wkoQs9c6GPWsmt7dptVM21RMPjZ0=,tag:JY10abptfm5Q4B0jwd4BSg==,type:str]
        project: ENC[AES256_GCM,data:0NfATUXsbg==,iv:f42K33tY6Rh4/BH8QELHAY81paVRCID37tQfdjLodPs=,tag:i0NI6LfUsOZaIdR9OPW+Ew==,type:str]
        source:
            helm:
                valueFiles:
                    - ENC[AES256_GCM,data:wiygHoSt0FhFNvvpiGoiJ/CA3AisGA==,iv:quiNNosQZedmuCXOM6joaoksEo09Oe02mHhW9tPKQGs=,tag:rtvBRQRxX6NcftdR/KUXsA==,type:str]
            path: ENC[AES256_GCM,data:JKfJ5UneZTTnqDJpr56oxSw=,iv:GhdOPZhuwOE4AReIw020frl1Kx7DYWHfDkGC01YhkJ0=,tag:PaUMApDuwS0DlR9RiK1Xdw==,type:str]
            repoURL: ENC[AES256_GCM,data:/+H8KmOun+4zdk/IbB6ePhoC/ltN5emLzUBP+HTv/AGJjtbmGw5JGCph6b63rTovaP58Zg7I,iv:a3BAaTDoe6UZ9QjpKx/bvWaNm7KQ5u+iTlgRipGCgAI=,tag:4k/Ma2zp9pIGGcM8btnp0w==,type:str]
        destination:
            namespace: ENC[AES256_GCM,data:08vixPbz,iv:sJsx8/tjsWz+BU43BT5YfqcdAAgu7N3txLi2Q6Opyok=,tag:URtehPM38zyFMhs3rL4gNA==,type:str]
            server: ENC[AES256_GCM,data:ThW7vYiau65SxGkZIE4eJSBDAu48yKTbRfQdqA/p,iv:ybxAqe8otzZCehY0GoGF/c40H17BdIdHc7GZiwHz1Sg=,tag:WiK/9Jv4Y5ZltdMRq3dxCg==,type:str]
        syncPolicy:
            automated: {}
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c9zz7wdv56gdsycv5l60zhjeng7y4gtm7qhzd9qrzc2e332lk3vsrwsxuy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRzJMZ0tmMG1lOVBIVGFq
            QzFNRWZHMnZIYnZZVHd6cVBwL1c3ZmNWT1h3CnRwWmgwTHhuQVkyZFBra1lJbjRp
            YklCZ1VJcUhCL01uUUJaNFlyeUhpRXMKLS0tIEhOblpQRHgxVTRIWDMxREJrS29P
            dkJpVGs2aFpKZ0RqSWpvQnlRb1hLVDQKncebzduKOm5khB/1Bj2MiuxT7ZdWa0Pw
            v7NH14M0AfvrxF+d6aFMilKMPEg8jOxEu97dfZKfzILNlY/H6YkXmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-20T16:57:02Z"
    mac: ENC[AES256_GCM,data:mM99x3+KHYV594mHMQwSQoRnYREk+QtucqyM6nlIbXvFByrqua4cW0sKRUt2NYE4ljEnCFYMdPm6vkbfmjjbd6zufbgDkU9CNmLWuF0KIHctIZ1uD0cVRQlge7nhmtp080CyDIODApYQBGkUPwB+3arscIb5D6Z+1yM/qJa6obk=,iv:pl9nRIJSme/teNn6QfWvEFjqnocYcUkh5MbgXbJWw38=,tag:CoKA3Omx3/1v+9xgfX3W2A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
